addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn"                % "0.1.3")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.6.4")
addSbtPlugin("org.scala-js"     % "sbt-scalajs"               % "1.16.0")
addSbtPlugin("org.typelevel"    % "sbt-typelevel"             % "0.7.3")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-scalafix"    % "0.7.3")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-site"        % "0.7.3")
